// <auto-generated />
namespace BackEndTesteGrupoRovema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CriandoRelacionamentoentreclassesProdutoeCategoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CriandoRelacionamentoentreclassesProdutoeCategoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201902192108431_Criando Relacionamento entre classes Produto e Categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
